{% set name = "jinjasql" %}
{% set version = "0.1.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/sripathikrishnan/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 91d2362311443bcff6d91fc948e932d346f4ab738006c64adb1e4d4323f679b6
  patches:
    - fix_jinja2.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - m2-patch  # [win]
    - patch     # [not win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - jinja2 >=2.8

test:
  imports:
    - jinjasql
  source_files:
    - tests/
    - run_tests
  requires:
    - django
    - pip
    - pytest
    - pyyaml
  commands:
    - pip check
    - python run_tests

about:
  home: https://github.com/sripathikrishnan/jinjasql
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Template Language for SQL with Automatic Bind Parameter Extraction
  description: |
    JinjaSQL is a template language for SQL statements and scripts. Since it's
    based in Jinja2, you have all the power it offers - conditional statements,
    macros, looping constructs, blocks, inheritance, and many more.
  dev_url: https://github.com/sripathikrishnan/jinjasql
  doc_url: https://github.com/sripathikrishnan/jinjasql

extra:
  recipe-maintainers:
    - scopatz
